"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$hostname\
$directory\
$git_branch$git_status\
$fill\
$python\
$aws\
$container\
$cmd_duration\
$time\
$line_break\
$character"""

palette = 'ayu_dark'

[palettes.ayu_dark]
accent = "#E6B450"
foreground = "#BFBDB6"
muted = "#5A6378"
green = "#70BF56"
blue = "#73B8FF"
cyan = "#39BAE6"
red = "#D95757"
purple = "#D2A6FF"

[os]
format = '[$symbol ]($style)'
disabled = false

[os.symbols]
Debian = "🌀 "
Macos = ' '
Ubuntu = ' '
Windows = ' '

[username]
show_always = true
format = '[$user]($style) '

[hostname]
format = '[$ssh_symbol$hostname]($style): '

[directory]
truncation_symbol = '.../'

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
always_show_remote = true

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = "=${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "*${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[fill]
symbol = '─'
style = 'fg:muted'

[python]
format = '[ $symbol( $version)(\(#$virtualenv\)) ]($style)'

[aws]
symbol = '🅰 '

[cmd_duration]
min_time = 3000
format = '[ $duration ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:foreground"
format = '[  $time ]($style)'
