"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$directory\
$git_branch$git_status\
$fill\
$python\
$aws\
$cmd_duration\
$time\
$hostname\
$line_break\
$character"""

palette = 'ayu_dark'

[palettes.ayu_dark]
accent = "#E6B450"
foreground = "#BFBDB6"
muted = "#5A6378"
green = "#70BF56"
blue = "#73B8FF"
cyan = "#39BAE6"
red = "#D95757"
purple = "#D2A6FF"

[os]
disabled = true
style = 'bold fg:blue'
format = '[ $symbol]($style)'

[os.symbols]
Ubuntu = ' '
Windows = ' '
Macos = ' '

[directory]
style = "bold fg:accent"
format = "[ $path ]($style)"
truncation_length = 6
truncation_symbol = ' '
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bold fg:green"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bold fg:green"
format = '[($all_status$ahead_behind )]($style)'

[fill]
symbol = '─'
style = 'fg:muted'

[python]
symbol = ""
style = "fg:cyan"
format = '[ $symbol( $version)(\(#$virtualenv\)) ]($style)'

[aws]
format = '[$symbol ($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = '🅰 '

[cmd_duration]
min_time = 3000
style = 'fg:accent'
format = '[ $duration ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:foreground"
format = '[  $time ]($style)'

[hostname]
ssh_only = true
format = '[$ssh_symbol$hostname]($style) '
ssh_symbol = '🌐 '
style = 'bold yellow'
disabled = false

[character]
success_symbol = '[❯](bold fg:accent)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:accent)'
vimcmd_replace_one_symbol = '[❮](bold fg:purple)'
vimcmd_replace_symbol = '[❮](bold fg:purple)'
vimcmd_visual_symbol = '[❮](bold fg:accent)'
